/** DOT completion data — attribute value domains and colors for autocomplete.
 * The keyword/attribute vocabulary lives in core/dot-vocab (shared with the CLI). */

export const DOT_ATTR_VALUES: Record<string, readonly string[]> = {
  shape: [
    'box',
    'polygon',
    'ellipse',
    'oval',
    'circle',
    'point',
    'egg',
    'triangle',
    'plaintext',
    'plain',
    'diamond',
    'trapezium',
    'parallelogram',
    'house',
    'pentagon',
    'hexagon',
    'septagon',
    'octagon',
    'doublecircle',
    'doubleoctagon',
    'invtriangle',
    'invtrapezium',
    'record',
    'Mrecord',
    'note',
    'tab',
    'folder',
    'box3d',
    'component',
    'cylinder',
    'star',
    'none',
  ],
  style: [
    'filled',
    'invisible',
    'invis',
    'diagonals',
    'rounded',
    'dashed',
    'dotted',
    'solid',
    'bold',
    'wedged',
    'striped',
    'radial',
  ],
  rankdir: ['TB', 'LR', 'BT', 'RL'],
  dir: ['forward', 'back', 'both', 'none'],
  arrowhead: [
    'normal',
    'inv',
    'dot',
    'invdot',
    'odot',
    'invodot',
    'none',
    'tee',
    'empty',
    'diamond',
    'ediamond',
    'box',
    'open',
    'crow',
    'vee',
  ],
  arrowtail: [
    'normal',
    'inv',
    'dot',
    'invdot',
    'odot',
    'invodot',
    'none',
    'tee',
    'empty',
    'diamond',
    'ediamond',
    'box',
    'open',
    'crow',
    'vee',
  ],
  rank: ['same', 'min', 'source', 'max', 'sink'],
  splines: ['true', 'false', 'none', 'line', 'polyline', 'curved', 'ortho', 'spline'],
  overlap: ['true', 'false', 'scale', 'prism', 'compress', 'vpsc'],
  ratio: ['fill', 'compress', 'expand', 'auto'],
};

export const DOT_COLORS = [
  'black',
  'white',
  'gray',
  'grey',
  'red',
  'green',
  'blue',
  'yellow',
  'orange',
  'purple',
  'pink',
  'brown',
  'cyan',
  'magenta',
  'lightgray',
  'lightgrey',
  'lightblue',
  'darkgreen',
  'navy',
  'gold',
  'silver',
  'transparent',
] as const;

const COLOR_ATTRIBUTES = new Set(['color', 'bgcolor', 'fillcolor', 'fontcolor']);

export function isColorAttribute(attr: string): boolean {
  return COLOR_ATTRIBUTES.has(attr.toLowerCase());
}
