import type { Analysis, ModuleEdges, ModuleMap } from './types';

export function renderMermaid(modules: ModuleMap, edges: ModuleEdges): string {
  const lines = ['graph LR'];
  for (const mod of [...modules.keys()].sort()) lines.push(`  ${mod}["${mod}"]`);
  for (const [from, tos] of [...edges.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    for (const to of [...tos].sort()) lines.push(`  ${from} --> ${to}`);
  }
  return `${lines.join('\n')}\n`;
}

export function renderJson(a: Analysis): string {
  const model = {
    stats: a.stats,
    modules: Object.fromEntries(a.modules),
    moduleEdges: Object.fromEntries([...a.moduleEdges].map(([k, v]) => [k, [...v]])),
    cycles: a.cycles,
    unused: a.unused,
    coverage: a.coverage,
    ipc: a.ipc,
    files: a.files.map((f) => ({ path: f.path, loc: f.loc, exports: f.exports })),
  };
  return `${JSON.stringify(model, null, 2)}\n`;
}

function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(' | ')} |`;
  const sep = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((r) => `| ${r.join(' | ')} |`).join('\n');
  return `${head}\n${sep}\n${body || `| ${headers.map(() => '—').join(' | ')} |`}`;
}

export function renderMarkdown(a: Analysis): string {
  const s = a.stats;
  const out: string[] = [];
  out.push('# GraphvizJS Dependency Graph');
  out.push('');
  out.push('> Generated by `pnpm graph`. Do not edit by hand — regenerate instead.');
  out.push('');
  out.push('## Summary');
  out.push('');
  out.push(
    table(
      ['Metric', 'Value'],
      [
        ['Files', String(s.fileCount)],
        ['Modules', String(s.moduleCount)],
        ['Lines of code', String(s.totalLoc)],
        ['Internal edges', String(s.edgeCount)],
        ['Exports', String(s.exportCount)],
      ]
    )
  );
  out.push('');

  out.push('## Modules');
  out.push('');
  for (const mod of [...a.modules.keys()].sort()) {
    out.push(`### ${mod}`);
    out.push('');
    for (const f of a.modules.get(mod) ?? []) out.push(`- \`${f}\``);
    out.push('');
  }

  out.push('## Module dependencies');
  out.push('');
  out.push(
    table(
      ['Module', 'Depends on'],
      [...a.moduleEdges.entries()]
        .sort((x, y) => x[0].localeCompare(y[0]))
        .map(([from, tos]) => [from, [...tos].sort().join(', ')])
    )
  );
  out.push('');

  out.push('## Circular dependencies');
  out.push('');
  if (a.cycles.runtime.length === 0 && a.cycles.typeOnly.length === 0) {
    out.push('None. ✅');
  } else {
    for (const c of a.cycles.runtime) out.push(`- ⚠️ runtime: ${c.join(' → ')}`);
    for (const c of a.cycles.typeOnly) out.push(`- 🔸 type-only: ${c.join(' → ')}`);
  }
  out.push('');

  out.push('## Unused');
  out.push('');
  out.push(`**Unused files:** ${a.unused.unusedFiles.length === 0 ? 'none ✅' : ''}`);
  for (const f of a.unused.unusedFiles) out.push(`- \`${f}\``);
  out.push('');
  out.push(`**Unused exports:** ${a.unused.unusedExports.length === 0 ? 'none ✅' : ''}`);
  for (const e of a.unused.unusedExports) out.push(`- \`${e.name}\` in \`${e.file}\``);
  out.push('');

  out.push('## Test coverage (src ↔ test)');
  out.push('');
  out.push(
    table(
      ['Source file', 'Tests'],
      a.coverage.map((r) => [
        `\`${r.file}\``,
        r.testFiles.length ? r.testFiles.map((t) => `\`${t}\``).join(', ') : '—',
      ])
    )
  );
  out.push('');

  out.push('## IPC boundary (renderer ↔ Electron)');
  out.push('');
  const ipcRows: string[][] = [];
  for (const c of a.ipc.fullyWired) ipcRows.push([`\`${c.channel}\``, c.method ?? '', '✅ wired']);
  for (const c of a.ipc.missingContract) {
    ipcRows.push([`\`${c.channel}\``, c.method ?? '', '⚠️ no contract']);
  }
  for (const c of a.ipc.missingHandlers) {
    ipcRows.push([`\`${c.channel}\``, c.method ?? '', '⚠️ no handler']);
  }
  for (const c of a.ipc.orphanHandlers) {
    ipcRows.push([`\`${c.channel}\``, c.method ?? '', '🔸 orphan handler']);
  }
  out.push(table(['Channel', 'Method', 'Status'], ipcRows));
  out.push('');
  out.push(
    '> `import.meta.glob` example/module loads (Vite) are not static imports and are excluded from edge resolution.'
  );
  out.push('');
  return out.join('\n');
}
