graph LR
  autosave["autosave"]
  cli["cli"]
  core["core"]
  editor["editor"]
  electron["electron"]
  help["help"]
  menu["menu"]
  platform["platform"]
  preview["preview"]
  recent["recent"]
  root["root"]
  session["session"]
  tabs["tabs"]
  toolbar["toolbar"]
  utils["utils"]
  watch["watch"]
  window["window"]
  workspace["workspace"]
  cli --> core
  editor --> core
  electron --> core
  electron --> menu
  electron --> platform
  electron --> watch
  help --> platform
  menu --> platform
  platform --> core
  preview --> core
  preview --> utils
  recent --> platform
  root --> autosave
  root --> core
  root --> editor
  root --> help
  root --> menu
  root --> platform
  root --> preview
  root --> recent
  root --> session
  root --> tabs
  root --> toolbar
  root --> watch
  root --> window
  root --> workspace
  session --> autosave
  session --> core
  session --> platform
  tabs --> core
  toolbar --> core
  toolbar --> editor
  toolbar --> platform
  watch --> platform
  window --> platform
